name: Deploy Frontend to Vercel on Develop Push (if E2E passed)

permissions:
  contents: write

on:
  workflow_run:
    workflows: ["CI - Pruebas E2E Frontend"]
    types:
      - completed

jobs:
  deploy-develop:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy to Vercel - Develop
    runs-on: ubuntu-latest
    environment:
      name: develop-deploy
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
      - name: Deploy develop on Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          alias-domains: ${{ secrets.DEVELOP_ALIAS_DOMAIN }}

  deploy-qa:
    name: Merge and Deploy QA
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: deploy-develop
    runs-on: ubuntu-latest
    environment:
      name: qa-deploy
    steps:
      - name: Checkout QA branch
        uses: actions/checkout@v3
        with:
          ref: qa
      - name: Configurar Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
      - name: Merge develop en qa
        run: |
          git fetch origin develop
          git merge origin/develop --no-edit
          git push origin qa
      - name: Deploy QA en Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          alias-domains: ${{ secrets.QA_ALIAS_DOMAIN }}
